---
sponsors_2015:
sponsors_2014:
  - name: 'USG'
    website: 'http://usg.case.edu'
    image: 'usg-logo.png'
  - name: 'Yelp'
    website: 'http://www.yelp.com'
    image: 'yelp-logo.png'
  - name: 'Co-op office'
    website: 'http://engineering.case.edu/coop'
    image: 'coop-logo.jpg'
  - name: 'BoxCast'
    website: 'https://www.boxcast.com'
    image: 'boxcast.png'
  - name: 'Framed Data'
    website: 'http://framed.io'
    image: 'framed-data.png'
  - name: 'CameraLends'
    website: 'https://www.cameralends.com'
    image: 'cameralends.jpg'
  - name: 'MIM Software'
    website: 'http://www.mimsoftware.com'
    image: 'mim-logo.png'
  - name: 'Mongoose Metrics'
    website: 'https://www.mongoosemetrics.com'
    image: 'mongoose-metrics.png'
sponsors_2013:
  - name: 'USG'
    website: 'http://usg.case.edu'
    image: 'usg-logo.png'
  - name: 'Yelp'
    website: 'http://www.yelp.com'
    image: 'yelp-logo.png'
  - name: 'Causes'
    website: 'http://www.causes.com'
    image: 'causes-logo.png'
  - name: 'VK'
    website: 'http://www.vkcareers.com'
    image: 'vklogo.png'
  - name: 'Google'
    website: 'http://www.google.com'
    image: 'google-logo.png'
  - name: 'Microsoft'
    website: 'http://www.microsoft.com'
    image: 'microsoft-logo.png'
  - name: 'LeanDog'
    website: 'http://www.leandog.com'
    image: 'leandog.png'
