---
sponsors_2015:
sponsors_2014:
  # Note that some sponsors re-use 2013 logos
  - name: 'USG'
    website: 'http://usg.case.edu'
    image: 'sponsors_ls_2013/usg-logo.png'
  - name: 'Yelp'
    website: 'http://www.yelp.com'
    image: 'sponsors_ls_2013/yelp-logo.png'
  - name: 'Co-op office'
    website: 'http://engineering.case.edu/coop'
    image: 'sponsors_ls_2014/coop-logo.jpg'
  - name: 'BoxCast'
    website: 'https://www.boxcast.com'
    image: 'sponsors_ls_2014/boxcast.png'
  - name: 'Framed Data'
    website: 'http://framed.io'
    image: 'sponsors_ls_2014/framed-data.png'
  - name: 'CameraLends'
    website: 'https://www.cameralends.com'
    image: 'sponsors_ls_2014/cameralends.jpg'
  - name: 'MIM Software'
    website: 'http://www.mimsoftware.com'
    image: 'sponsors_ls_2014/mim-logo.png'
  - name: 'Mongoose Metrics'
    website: 'https://www.mongoosemetrics.com'
    image: 'sponsors_ls_2014/mongoose-metrics.png'
sponsors_2013:
  - name: 'USG'
    website: 'http://usg.case.edu'
    image: 'sponsors_ls_2013/usg-logo.png'
  - name: 'Yelp'
    website: 'http://www.yelp.com'
    image: 'sponsors_ls_2013/yelp-logo.png'
  - name: 'Causes'
    website: 'http://www.causes.com'
    image: 'sponsors_ls_2013/causes-logo.png'
  - name: 'VK'
    website: 'http://www.vkcareers.com'
    image: 'sponsors_ls_2013/vklogo.png'
  - name: 'Google'
    website: 'http://www.google.com'
    image: 'sponsors_ls_2013/google-logo.png'
  - name: 'Microsoft'
    website: 'http://www.microsoft.com'
    image: 'sponsors_ls_2013/microsoft-logo.png'
  - name: 'LeanDog'
    website: 'http://www.leandog.com'
    image: 'sponsors_ls_2013/leandog.png'
